course = 'Python for Beginners'
print(len(course))
print(course.upper())
print(course.lower())
print(course.find('P'))
print(course.find('o'))
print(course.find('O'))
print(course.find('Beginners'))
print(course.replace('P','J'))
print(course.replace('Beginners','Absolute Beginners'))
print(course.replace('beginners','Absolute Beginners'))
print('Python' in course)
print('python' in course)
print(course)